# Generated by Django 4.2 on 2023-08-06 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaystackTag',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('created_at', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('format', models.JSONField()),
                ('protocol', models.CharField(choices=[('HTTP', 'Http'), ('MQTT', 'Mqtt')], default='HTTP', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor_driver.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('created_at', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=100)),
                ('measure', models.CharField(choices=[('SECONDS', 'Seconds'), ('MINUTES', 'Minutes'), ('HOURS', 'Hours')], default='MINUTES', max_length=20)),
                ('timeline', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensor_driver.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headers', models.JSONField(null=True)),
                ('params', models.JSONField(null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensor_driver.sensor')),
            ],
        ),
    ]
