# Generated by Django 4.2 on 2023-06-17 04:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('series', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Enter field documentation', primary_key=True, serialize=False)),
                ('protocol', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('headers', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('format', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('sensor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sensor_driver.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('uri', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('frequency', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('timeline', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('sensor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sensor_driver.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor_driver.zone'),
        ),
    ]
