apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: zenith-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:3.9-management"
          ports:
            - containerPort: 5672  # Puerto para conexiones AMQP
            - containerPort: 15672  # Puerto para el panel de control de RabbitMQ
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "dary"
            - name: RABBITMQ_DEFAULT_PASS
              value: "dary"