kind: Deployment
apiVersion: apps/v1
metadata:
   name: influxdb
   namespace: zenith-beta
spec:
   replicas: 1
   selector:
      matchLabels:
         app: influxdb
   template:
      metadata:
         labels:
            app: influxdb
      spec:
         containers:
            - name: influxdb
              image: quay.io/influxdb/influxdb:v2.0.2
              volumeMounts:
              - mountPath: /root/.influxdbv2/
                name: influxdb-data
              ports:
                - containerPort: 8086
         volumes:
         - name: influxdb-data
           persistentVolumeClaim:
             claimName: influxdb-pvc  # Nombre del PVC que crearemos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: zenith-beta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Tamaño del almacenamiento solicitado
