services:
  web:
    container_name: web-zenith
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - zenith
  db:
    container_name: mysql-test
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: zenith
      MYSQL_ROOT_PASSWORD: zenith
      MYSQL_USER:  zenith
      MYSQL_PASSWORD: zenith
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - zenith

      
  #rabbitmq:
   # image: rabbitmq:3.11-management
    #container_name: rabbitmq-test
   # tty: true
    #ports:
   #   - "5672:5672"
    #  - "15672:15672"
    #environment:
    #  RABBITMQ_DEFAULT_USER: "guest"
     # RABBITMQ_DEFAULT_PASS: "guest"
     # RABBITMQ_DEFAULT_VHOST: "/"
 
  #  networks:
   #   - zenith

networks:
  zenith:
    driver: bridge


volumes:
  mysql-data:
