services:
  web:
    container_name: web-zenith
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: zenith
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  db:
    container_name: mysql-zenith
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: zenith
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
